python train.py \
    --batch_size bs \
    --run_name run/train \
    --epoch 5000 \
    --train_steps 20000 \
    --test_steps 500 \
    --save_steps 5000 \
    --log_steps 50 \
    --warmup_steps 100 \
    --save_dir ./save \
    --lr 0.003 \
    --weight_decay 0 \
    --gpu 0 \
    --use_batch_norm \
    --use_drop_out \
    --drop_out_prob 0.5	\
    --test_curve	\
    --seed 2019